-- Create a user
--alter session set "_ORACLE_SCRIPT"=true;
--CREATE USER SANKHASCHEMA IDENTIFIED BY Admin123;
--GRANT CONNECT TO SANKHASCHEMA;
--Grant permissions
--GRANT CONNECT, RESOURCE, DBA TO demo;
-- USER SQL
ALTER USER "SANKHASCHEMA"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "SANKHASCHEMA" DEFAULT ROLE "CONNECT";

-- SYSTEM PRIVILEGES


CREATE TABLE SANKHASCHEMA.superheroes (
  sh_name VARCHAR2 (15)
);

CREATE OR REPLACE TRIGGER bi_Superheroes
BEFORE INSERT ON SANKHASCHEMA.superheroes
FOR EACH ROW
ENABLE
DECLARE
  v_user  VARCHAR2 (15);
BEGIN
 SELECT user INTO v_user FROM dual;
 DBMS_OUTPUT.PUT_LINE('You Just Inserted a Row Mr.'|| v_user); 
END;
/

